### ISSUE TITLE
Desactivar plugins activados que no se estén utilizando

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/wp-plugins#1]
Ping @stripTM @willyaranda @nukeador para saber si podemos borrar los siguientes plugins:
- Google Social Analytics Extension (extends your Google Analytics): Extend your Google Analytics to track social buttons like the Facebook "like" , the Twitter "Tweet"
- W3 Total Cache (se está usando Quick Cache)

El plugin de All in One SEO Pack no se está usando ahora mismo pero deberíamos. ![Issue relacionado.](https://github.com/mozillahispano/mozilla-hispano.org/issues/20)

**Comment by stripTM** [comment]
Pues yo creo que si que se pueden borrar, un +1 por mi lado.

**Comment by fjaguero** [comment]
Ok :+1:

**Comment by nukeador** [comment]
Si hay plugins desactivados que no se están usando, se pueden borrar sin problema.

**Comment by fjaguero** [comment]
En este caso el primero está activado, pero si ya no se usa GA no tiene sentido. Lo desactivo y borro.
